In [47]:
# %pip install numpy pandas matplotlib scikit-learn

In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [49]:
df=pd.read_csv('data.csv')
df.head()

param1  param2  param3  param4  param5  param6  output
0    0.12    0.34    0.23    0.45    0.18    0.29       0
1    0.78    0.82    0.91    0.76    0.88    0.85       1
2    0.25    0.19    0.31    0.22    0.27    0.15       0
3    0.89    0.76    0.84    0.91    0.79    0.92       1
4    0.15    0.28    0.17    0.33    0.21    0.24       0

In [50]:
from sklearn.model_selection import train_test_split
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
len(x_train), len(x_test)

(96, 24)

In [ ]:
import random
class NN:
    def __init__(self,n_features, hidden_units):
        self.w1=np.random.randn(n_features, hidden_units)
        self.b1=np.zeros(hidden_units)

        self.w2=np.random.randn(hidden_units)
        self.b2=0

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def log_loss(self, y_true, y_predicted):
        n=len(y_true)
        loss= - np.mean(y_true*np.log(y_predicted)+(1-y_true)*np.log(1-y_predicted))
        return loss
    
    def fit(self,x,y,epochs,loss_treshld):
        x=x.values
        y=y.values

        self.gradientDescent(x,y,epochs) 
    
    def predict(self, x_test):
        x=x_test.values

        z1=np.dot(x,self.w1)+self.b1
        a1=self.sigmoid(z1)

        z2=np.dot(a1,self.w2)+self.b2
        y_pred=self.sigmoid(z2)

        return y_pred

    def gradientDescent(self, x,y_true, epochs):
        n=x.shape[0]
        rate=0.5
        for i in range(epochs):
            #forward pass
            z1=np.dot(x,self.w1)+self.b1
            a1=self.sigmoid(z1)

            z2=np.dot(a1,self.w2)+self.b2
            y_pred=self.sigmoid(z2)


            #loss calculation
            loss=self.log_loss(y_true, y_pred)

            #backpropogation
            dz2=y_pred-y_true
            dw2=(1/n)*np.dot(a1.T,dz2)
            db2=np.mean(dz2)

            dz1=np.outer(dz2,self.w2)*a1*(1-a1)
            dw1=(1/n)*np.dot(x.T,dz1)
            db1=np.mean(dz1, axis=0)

            #update weights
            self.w2-=rate*dw2
            self.b2-=rate*db2
            self.w1-=rate*dw1
            self.b1-=rate*db1

            print(f"Epoch: {i+1}, Loss: {loss}, W1: {self.w1}, b1: {self.b1}, W2: {self.w2}, b2: {self.b2}")

    
    

In [52]:
# custom=NN()
# w,b,cost,cost_list,epochs_list=custom.stochastic_gradient_descend(x_train.values,y_train.values,500)
# w, b, cost, cost_list, epochs_list

In [54]:
customModel = NN(n_features=x_train.shape[1],hidden_units=5)
customModel.fit(x_train, y_train, epochs=500, loss_treshld=0.46)

Epoch: 1, Loss: 0.7979083602882696, W1: [[-0.67948983  0.078386    0.25854907 -0.95687047  1.14669345]
 [-0.95845514 -1.09181945 -1.40310927  0.47248347 -0.49165714]
 [-1.04911854  0.13467814  1.98378383  0.86127135 -0.54157962]
 [-0.8411321  -0.21494229  0.21348259 -0.74475471  0.16438876]
 [-0.24399886 -0.15249349  0.86937981  1.09776764 -0.89469   ]
 [-1.42381937  1.02941107 -0.63821176 -2.34656318 -0.41055417]], b1: [ 0.00941856  0.00641301  0.00341997  0.00416878 -0.04006757], W2: [-0.42285693 -0.85537801 -0.23649174 -0.2813216   2.85229758], b2: -0.03030087191616768
Epoch: 2, Loss: 0.7706050340235334, W1: [[-0.67733485  0.0641104   0.25610116 -0.9590152   1.18103398]
 [-0.9563671  -1.10643995 -1.40563219  0.47023441 -0.45626291]
 [-1.04689873  0.12037696  1.98134347  0.85914044 -0.507291  ]
 [-0.8388584  -0.22896003  0.21111604 -0.74681357  0.19785683]
 [-0.2416573  -0.166241    0.8670731   1.09578203 -0.86209462]
 [-1.42163927  1.01517526 -0.64063603 -2.34869125 -0.37638337]], b

In [55]:
y_pred=customModel.predict(x_test)

In [56]:
comparison_df = pd.DataFrame({'Real': y_test, 'Predicted': y_pred})
comparison_df

Real  Predicted
44      0   0.007511
47      1   0.990718
4       0   0.005929
55      1   0.990328
26      0   0.009785
64      0   0.010480
73      1   0.990910
10      0   0.005817
40      0   0.012587
107     1   0.991670
18      0   0.005945
62      0   0.006868
11      1   0.989499
36      0   0.005255
89      1   0.991615
91      1   0.991667
109     1   0.991666
0       0   0.011629
88      0   0.006320
104     0   0.009944
65      1   0.991017
45      1   0.990959
31      1   0.990275
70      0   0.010012

In [57]:
y_pred

array([0.00751129, 0.99071776, 0.00592924, 0.99032789, 0.0097852 ,
       0.01048043, 0.99090996, 0.00581733, 0.01258654, 0.99166973,
       0.00594508, 0.00686848, 0.98949857, 0.00525467, 0.99161482,
       0.99166675, 0.99166559, 0.01162937, 0.00631951, 0.00994448,
       0.99101735, 0.99095913, 0.99027493, 0.01001218])

In [58]:
# Calculate training loss
y_train_pred = customModel.predict(x_train)
train_loss = customModel.log_loss(y_train, y_train_pred)

# Calculate test loss
y_test_pred = customModel.predict(x_test)
test_loss = customModel.log_loss(y_test, y_test_pred)

print(f"Training Loss: {train_loss}")
print(f"Test Loss: {test_loss}")

if train_loss < test_loss * 0.8: # Arbitrary threshold for demonstration
    print("Potential Overfitting: Training loss is significantly lower than test loss.")
else:
    print("Model seems to be generalizing well.")

Training Loss: 0.008772524927182807
Test Loss: 0.008696179683688273
Model seems to be generalizing well.


In [59]:
x_train

param1  param2  param3  param4  param5  param6
42     0.21    0.33    0.18    0.26    0.29    0.22
12     0.28    0.16    0.33    0.21    0.25    0.22
15     0.93    0.88    0.85    0.94    0.82    0.91
114    0.24    0.31    0.27    0.18    0.33    0.22
76     0.19    0.31    0.26    0.21    0.29    0.18
..      ...     ...     ...     ...     ...     ...
106    0.23    0.17    0.29    0.21    0.26    0.19
14     0.34    0.21    0.29    0.18    0.32    0.26
92     0.31    0.22    0.26    0.33    0.24    0.19
51     0.88    0.92    0.87    0.89    0.91    0.86
102    0.13    0.28    0.23    0.31    0.19    0.26

[96 rows x 6 columns]